import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-industrial-gas-invoice-contract-audit",
  "engine": "recovery",
  "title": "Industrial Gas Invoice & Contract Audit",
  "shortTitle": "Industrial Gas Invoice and Contract Audit",
  "tagline": "Quantify, recover, and prevent financial leakage through industrial gas invoice & contract audit",
  "industry": "Industrial Gas Spend Recovery",
  "uiPort": 4609,
  "apiPort": 5609,
  "accent": "#c2410c",
  "currency": "USD",
  "primaryOutcome": "Industrial Gas Invoice & Contract Audit converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect gas supply contracts, sites, tanks, meters, products, purity specifications, volumes, indexes, take-or-pay terms, deliveries, rentals, telemetry, surcharges, invoices, and credits in one accountable recovery workflow.",
  "calculation": {
    "actualKey": "billedAmount",
    "expectedKey": "supportedAmount",
    "actualLabel": "Supplier Billed Amount",
    "expectedLabel": "Contract-Supported Amount",
    "varianceLabel": "Potential recovery or avoided cost",
    "direction": "actual-minus-expected",
    "finding": "Industrial Gas Invoice & Contract Audit evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective governing agreement and applicable rules",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare and submit the recovery or correction package",
      "Track counterparty response and reconcile realized outcome"
    ]
  }
},[
feature("supply-contract-library","IGI01","Supply contract library","Execute supply contract library using gas supply contracts, sites, tanks, meters, products, purity specifications, volumes, indexes, take-or-pay terms, deliveries, rentals, telemetry, surcharges, invoices, and credits.","Produce a governed supply contract library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Site","text","Supplier / Site · Standard Case"],["caseReference","Supply contract library Reference","text","IGI01-2026-001"],["billedAmount","Supplier Billed Amount","currency",753000],["supportedAmount","Contract-Supported Amount","currency",647580],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Supply contract library case","Site tank meter registry case","Product purity specification case","Volume meter ingestion case","Index price calculation case"]}),
feature("site-tank-meter-registry","IGI02","Site tank meter registry","Execute site tank meter registry using gas supply contracts, sites, tanks, meters, products, purity specifications, volumes, indexes, take-or-pay terms, deliveries, rentals, telemetry, surcharges, invoices, and credits.","Produce a governed site tank meter registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Site","text","Supplier / Site · Standard Case"],["caseReference","Site tank meter registry Reference","text","IGI02-2026-001"],["billedAmount","Supplier Billed Amount","currency",753000],["supportedAmount","Contract-Supported Amount","currency",647580],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Supply contract library case","Site tank meter registry case","Product purity specification case","Volume meter ingestion case","Index price calculation case"]}),
feature("product-purity-specification","IGI03","Product purity specification","Execute product purity specification using gas supply contracts, sites, tanks, meters, products, purity specifications, volumes, indexes, take-or-pay terms, deliveries, rentals, telemetry, surcharges, invoices, and credits.","Produce a governed product purity specification decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Site","text","Supplier / Site · Standard Case"],["caseReference","Product purity specification Reference","text","IGI03-2026-001"],["billedAmount","Supplier Billed Amount","currency",753000],["supportedAmount","Contract-Supported Amount","currency",647580],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Supply contract library case","Site tank meter registry case","Product purity specification case","Volume meter ingestion case","Index price calculation case"]}),
feature("volume-meter-ingestion","IGI04","Volume meter ingestion","Execute volume meter ingestion using gas supply contracts, sites, tanks, meters, products, purity specifications, volumes, indexes, take-or-pay terms, deliveries, rentals, telemetry, surcharges, invoices, and credits.","Produce a governed volume meter ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Site","text","Supplier / Site · Standard Case"],["caseReference","Volume meter ingestion Reference","text","IGI04-2026-001"],["billedAmount","Supplier Billed Amount","currency",753000],["supportedAmount","Contract-Supported Amount","currency",647580],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Supply contract library case","Site tank meter registry case","Product purity specification case","Volume meter ingestion case","Index price calculation case"]}),
feature("index-price-calculation","IGI05","Index price calculation","Execute index price calculation using gas supply contracts, sites, tanks, meters, products, purity specifications, volumes, indexes, take-or-pay terms, deliveries, rentals, telemetry, surcharges, invoices, and credits.","Produce a governed index price calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Site","text","Supplier / Site · Standard Case"],["caseReference","Index price calculation Reference","text","IGI05-2026-001"],["billedAmount","Supplier Billed Amount","currency",753000],["supportedAmount","Contract-Supported Amount","currency",647580],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Supply contract library case","Site tank meter registry case","Product purity specification case","Volume meter ingestion case","Index price calculation case"]}),
feature("take-or-pay-validation","IGI06","Take-or-pay validation","Execute take-or-pay validation using gas supply contracts, sites, tanks, meters, products, purity specifications, volumes, indexes, take-or-pay terms, deliveries, rentals, telemetry, surcharges, invoices, and credits.","Produce a governed take-or-pay validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Site","text","Supplier / Site · Standard Case"],["caseReference","Take-or-pay validation Reference","text","IGI06-2026-001"],["billedAmount","Supplier Billed Amount","currency",753000],["supportedAmount","Contract-Supported Amount","currency",647580],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Supply contract library case","Site tank meter registry case","Product purity specification case","Volume meter ingestion case","Index price calculation case"]}),
feature("delivery-fee-audit","IGI07","Delivery fee audit","Execute delivery fee audit using gas supply contracts, sites, tanks, meters, products, purity specifications, volumes, indexes, take-or-pay terms, deliveries, rentals, telemetry, surcharges, invoices, and credits.","Produce a governed delivery fee audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Site","text","Supplier / Site · Standard Case"],["caseReference","Delivery fee audit Reference","text","IGI07-2026-001"],["billedAmount","Supplier Billed Amount","currency",753000],["supportedAmount","Contract-Supported Amount","currency",647580],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Supply contract library case","Site tank meter registry case","Product purity specification case","Volume meter ingestion case","Index price calculation case"]}),
feature("tank-rental-validation","IGI08","Tank rental validation","Execute tank rental validation using gas supply contracts, sites, tanks, meters, products, purity specifications, volumes, indexes, take-or-pay terms, deliveries, rentals, telemetry, surcharges, invoices, and credits.","Produce a governed tank rental validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Site","text","Supplier / Site · Standard Case"],["caseReference","Tank rental validation Reference","text","IGI08-2026-001"],["billedAmount","Supplier Billed Amount","currency",753000],["supportedAmount","Contract-Supported Amount","currency",647580],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Supply contract library case","Site tank meter registry case","Product purity specification case","Volume meter ingestion case","Index price calculation case"]}),
feature("telemetry-validation","IGI09","Telemetry validation","Execute telemetry validation using gas supply contracts, sites, tanks, meters, products, purity specifications, volumes, indexes, take-or-pay terms, deliveries, rentals, telemetry, surcharges, invoices, and credits.","Produce a governed telemetry validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Site","text","Supplier / Site · Standard Case"],["caseReference","Telemetry validation Reference","text","IGI09-2026-001"],["billedAmount","Supplier Billed Amount","currency",753000],["supportedAmount","Contract-Supported Amount","currency",647580],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Supply contract library case","Site tank meter registry case","Product purity specification case","Volume meter ingestion case","Index price calculation case"]}),
feature("emergency-delivery-audit","IGI10","Emergency delivery audit","Execute emergency delivery audit using gas supply contracts, sites, tanks, meters, products, purity specifications, volumes, indexes, take-or-pay terms, deliveries, rentals, telemetry, surcharges, invoices, and credits.","Produce a governed emergency delivery audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Site","text","Supplier / Site · Standard Case"],["caseReference","Emergency delivery audit Reference","text","IGI10-2026-001"],["billedAmount","Supplier Billed Amount","currency",753000],["supportedAmount","Contract-Supported Amount","currency",647580],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Supply contract library case","Site tank meter registry case","Product purity specification case","Volume meter ingestion case","Index price calculation case"]}),
feature("energy-surcharge-audit","IGI11","Energy surcharge audit","Execute energy surcharge audit using gas supply contracts, sites, tanks, meters, products, purity specifications, volumes, indexes, take-or-pay terms, deliveries, rentals, telemetry, surcharges, invoices, and credits.","Produce a governed energy surcharge audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Site","text","Supplier / Site · Standard Case"],["caseReference","Energy surcharge audit Reference","text","IGI11-2026-001"],["billedAmount","Supplier Billed Amount","currency",753000],["supportedAmount","Contract-Supported Amount","currency",647580],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Supply contract library case","Site tank meter registry case","Product purity specification case","Volume meter ingestion case","Index price calculation case"]}),
feature("minimum-volume-calculation","IGI12","Minimum volume calculation","Execute minimum volume calculation using gas supply contracts, sites, tanks, meters, products, purity specifications, volumes, indexes, take-or-pay terms, deliveries, rentals, telemetry, surcharges, invoices, and credits.","Produce a governed minimum volume calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Site","text","Supplier / Site · Standard Case"],["caseReference","Minimum volume calculation Reference","text","IGI12-2026-001"],["billedAmount","Supplier Billed Amount","currency",753000],["supportedAmount","Contract-Supported Amount","currency",647580],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Supply contract library case","Site tank meter registry case","Product purity specification case","Volume meter ingestion case","Index price calculation case"]}),
feature("invoice-recalculation","IGI13","Invoice recalculation","Execute invoice recalculation using gas supply contracts, sites, tanks, meters, products, purity specifications, volumes, indexes, take-or-pay terms, deliveries, rentals, telemetry, surcharges, invoices, and credits.","Produce a governed invoice recalculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Site","text","Supplier / Site · Standard Case"],["caseReference","Invoice recalculation Reference","text","IGI13-2026-001"],["billedAmount","Supplier Billed Amount","currency",753000],["supportedAmount","Contract-Supported Amount","currency",647580],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Supply contract library case","Site tank meter registry case","Product purity specification case","Volume meter ingestion case","Index price calculation case"]}),
feature("supplier-dispute-workflow","IGI14","Supplier dispute workflow","Execute supplier dispute workflow using gas supply contracts, sites, tanks, meters, products, purity specifications, volumes, indexes, take-or-pay terms, deliveries, rentals, telemetry, surcharges, invoices, and credits.","Produce a governed supplier dispute workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Site","text","Supplier / Site · Standard Case"],["caseReference","Supplier dispute workflow Reference","text","IGI14-2026-001"],["billedAmount","Supplier Billed Amount","currency",753000],["supportedAmount","Contract-Supported Amount","currency",647580],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Supply contract library case","Site tank meter registry case","Product purity specification case","Volume meter ingestion case","Index price calculation case"]}),
feature("site-product-analytics","IGI15","Site product analytics","Execute site product analytics using gas supply contracts, sites, tanks, meters, products, purity specifications, volumes, indexes, take-or-pay terms, deliveries, rentals, telemetry, surcharges, invoices, and credits.","Produce a governed site product analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Site","text","Supplier / Site · Standard Case"],["caseReference","Site product analytics Reference","text","IGI15-2026-001"],["billedAmount","Supplier Billed Amount","currency",753000],["supportedAmount","Contract-Supported Amount","currency",647580],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Supply contract library case","Site tank meter registry case","Product purity specification case","Volume meter ingestion case","Index price calculation case"]})
]);
